tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
# tap "redbubble/yak"
tap "sudar/arduino-mk"
brew "automake"
brew "bash-git-prompt"
brew "bison"
brew "chruby"
brew "direnv"
# brew "dnsmasq", restart_service: true
brew "fzf"
brew "gdbm"
brew "geoip"
brew "git"
brew "libffi"
brew "openssl"
brew "readline"
brew "htop"
# brew "imagemagick@6"
# brew "kubernetes-cli", link: false
brew "libyaml"
brew "midnight-commander"
brew "mysql"
brew "neovim"
# brew "nginx", restart_service: true
brew "pkg-config"
brew "node-build"
brew "nodenv"
brew "ripgrep"
brew "ruby-install"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "wget"
# brew "redbubble/yak/yak"
brew "sudar/arduino-mk/arduino-mk"
cask "brewtarget"
cask "firefox"
cask "gimp"
cask "godot"
cask "insomnia"
cask "kicad"
cask "libreoffice"
cask "openscad"
cask "prusa-slic3r"
