#! /bin/bash -e

command -v nvim >/dev/null 2>&1 || { echo >&2 "Please install neovim before continuing see https://neovim.io/"; exit 1; }

mkdir -p $HOME/.config/nvim/
[ ! -L $HOME/.config/nvim/init.vim ] && ln -s $(pwd)/neovim/init.vim $HOME/.config/nvim/init.vim

#
# Install neovim plugins
if [ ! -e ~/.local/share/nvim/site/autoload/plug.vim ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim -i NONE -c PlugInstall -c quitall

if grep "alias vim=nvim" $HOME/.bash_local > /dev/null
then
  echo "nvim alias already set"
else
  echo "alias vim=nvim" >> $HOME/.bash_local
  echo "An alias for nvim=vim has been set but won't take effect until you open a new terminal."
fi
