#! /bin/zsh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew bundle install
rm -f ~/.zcompdump; compinit
chmod -R go-w '/opt/homebrew/share/zsh'
compaudit | xargs chmod g-w
